
import { Inter } from 'next/font/google'
import '../globals.css'
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import Aside from '@/components/Aside';
import Header from '@/components/Header'
import Providers from '@/libs/themes/providers';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({ children, params }) {
  const locale = useLocale();
  const session = await getServerSession(authOptions)
 
  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }
  if (!session) {
    return <div className='w-full h-screen bg-black text-zinc-200 flex justify-center items-center flex-col'><h1 className='text-4xl text-primary font-inter mb-2'>Please log in to continue</h1>You are currently not logged in and do not have permission to access this page. <br />Please click the button below to log in before accessing.<a type="submit" class=" mt-6  rounded-full py-3 text-black font-medium w-1/3 bg-primary hover:bg-primary/80  border-indigo-500 hover:shadow inline-flex space-x-2 items-center justify-center">Login</a></div>
  }


  return (
    <html lang={locale}>
      <body className={inter.className}>
      <Providers> 
      <div className="flex flex-row w-full h-screen">
      <div className="w-[250px] md:block hidden flex-none">
          <Aside locale={locale} />
         
      </div>
          <div className="flex-1 overflow-auto h-screen w-full bg-zinc-200 dark:bg-black">

            <Header locale={locale} />
           
            <div className='h-full clac'>
            {children}         
            </div>
          </div>
        </div>
        </Providers>
      </body>
    </html>
  )
}
