
import AuthBrand from '@/components/AuthBrand'
import '../globals.css'
import { Toaster } from 'react-hot-toast'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }
  export default function RootLayout({ children, params }) {

    return (
      <>
      <Toaster position='top-center' />
        <div className='w-full h-screen flex flex-row bgg'>
          <div className='w-1/2 h-full hidden md:block'><AuthBrand /></div>
          <div className='w-full md:w-1/2 h-full relative flex bg-black items-center justify-center'>
            {children}
            <div className='absolute bottom-0 w-full h-5 flex justify-center '>d</div>
          </div>
        </div>
          
      </>
    )

  }